---
language: node_js
node_js:
- '0.6'
- '0.8'
- '0.10'
before_script:
  - npm install -g grunt-cli
script:
  - npm test
env:
  global:
	SAUCE_USERNAME=himanshu_panalinks
  - secure: |-
      aD7mio/oMmFPwHe/WKY+NRV45ChafsKQQF0kJGKvOw4sOGuKTyWc/K4Tf2lKbFz
			W+slPSdlCp1eTlrScbTuCl9euUU17BCrRXrF1v6KwwQi+ar7wsTiAu1OMiPC5k8
			f4KSHnXfnRUXRpUpM9fCP2sp0gzfBbgphlXap8KjP2e0Q=
matrix:
  include:
    - node_js: '0.10'
      script: grunt test
