language: node_js
before_script:
     - "npm install -g se-interpreter"
script:
     - "se-interpreter interpreter_config.json"
    
sauce_connect:
    username: "himanshu_panalinks"
    access_key: "297a9a01-7b3f-4cff-a894-320d342f1f2e"
